### ISSUE TITLE
Отсутствует возможность поиска по имени при добавлении пользователя

### ISSUE THREAD

**Issue by disovi** [lyaonov/vk-vue#1]
в задании явно было [не прописано](https://github.com/PeacockTeam/new-job/commit/840c51639a6972634688dc6b032729aee77202d8), что требуется автодополнение, но был приложен скриншот

![image](https://user-images.githubusercontent.com/705617/195123949-60748c77-cb1e-4bb5-8d0e-ab1bc29ab335.png)

**Comment by lyaonov** [comment]
Добавил поиск по имени

**Comment by disovi** [comment]
1. отсутвует автодополнение
2. есть возможность повторно добавить одного и того же пользователя

**Comment by lyaonov** [comment]
1. Поправил. по нажатию **Enter** добавляется пользователь из выпадающей подсказки
2. Поправил, больше нету :)
