### ISSUE TITLE
В списке друзей случайным образом отсутствуют данные о возрасте/количестве друзей

### ISSUE THREAD

**Issue by disovi** [lyaonov/vk-vue#2]
![image](https://user-images.githubusercontent.com/705617/195124618-c0c0840a-4ea8-4e48-a5ff-3c73b1556093.png)

при этом из под пользователя, для которого сгенерирован токен эти данные доступны.

**Comment by lyaonov** [comment]
поправил. 
там где указаны все данные, вычисляется возраст. При неполных данных, указывается день и месяц.
кол-во друзей добавил в карточку пользователя

**Comment by disovi** [comment]
количество друзей должно отображаться в списке.

**Comment by lyaonov** [comment]
поправил.
приложение будет подгружать для каждого друга с задержкой. т.к. в документации api

> Поле возвращается только в методе users.get при запросе информации об одном пользователе, с передачей пользовательского access_token.
